### ISSUE TITLE
spirvcrossj does not fall back to ContextClassLoader if using fat JAR

### ISSUE THREAD

**Issue by haesleinhuepf** [scenerygraphics/spirvcrossj#16]
Hey @skalarproduktraum ,

you may remember, we included Scenery at some point into ClearControl. I just tried updating the dependency to version 0.2.0-beta1.

I'm now getting this error message:
```
java.lang.NoClassDefFoundError: graphics/scenery/utils/SceneryJPanel
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:110)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:165)
	at clearcontrol.microscope.lightsheet.postprocessing.visualisation.instructions.SciViewInstruction.initialize(SciViewInstruction.java:57)
	at clearcontrol.microscope.lightsheet.timelapse.LightSheetTimelapse.acquire(LightSheetTimelapse.java:208)
	at clearcontrol.microscope.timelapse.TimelapseBase.loop(TimelapseBase.java:355)
	at clearcontrol.core.device.task.LoopTaskDevice.run(LoopTaskDevice.java:32)
	at clearcontrol.microscope.timelapse.TimelapseBase.run(TimelapseBase.java:301)
	at clearcontrol.core.device.task.TaskDevice.lambda$startTask$0(TaskDevice.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: graphics.scenery.utils.SceneryJPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

When calling:

```
SciViewService sciViewService = context.service( SciViewService.class );
SciView sciView = sciViewService.getOrCreateActiveSciView();
```
From: https://github.com/mpicbg-csbd/clearcontrol-lightsheet-csbd/blob/master/src/main/java/clearcontrol/microscope/lightsheet/postprocessing/visualisation/instructions/SciViewInstruction.java#L56

Is there some example code available showing how to generate a SciView instance from Java and load a volume into it?

Thanks a lot! No hurry btw.

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
Great. Thanks again for making it work @skalarproduktraum! Looking forward to explore the SciView API 😃

Closing this issue as it runs now nicely.

Cheers,
Robert

**Comment by skalarproduktraum** [comment]
Hi @haesleinhuepf, allow me to reopen this so I don't forget to add automagic fallback to the next spirvcrossj Loader version -- I will forget otherwise >_<

**Comment by skalarproduktraum** [comment]
As of 1879c72 the context class loader is used by default, so this should be fixed.
